### ISSUE TITLE
Linker Errors?

### ISSUE THREAD

**Issue by lylepratt** [onsip/onsip-cordova#5]
Just tried to install this plugin, but I'm getting tons of Linker errors. I've adjusted the Build Settings, Valid Architectures, etc, but none of that has helped. 

I'm running iOS 8.1 on an iPhone 4S. Am I missing something simple?

**Comment by InspectorConstructor** [comment]
I had the 110 linker errors also. They looked like C++ standard lib stuff, so I added the very latest libstdc++ (for me, libstdc++.6.0.9.dylib) to my "Link Binaries with Libraries" list in "Build Phases" in XCode. This solved the linker errors for me. @NayRia, if you're still getting these errors, I'd recommend trying this.

**Comment by LucasReyre** [comment]
Thanks @InspectorConstructor your solution works well

**Comment by AhsanAyaz** [comment]
@InspectorConstructor  DUDE !! You are a life saver. I've spent the whole day on this :/ It's my first day on ios build. VERY PAINFUL. 
Thanks. !!!!
